import os 
from dotenv import load_dotenv
load_dotenv()

GROQ_API_KEY = os.getenv("GROK_API_KEY")
DATABASE_URL = os.getenv("CONNECTION_STRING_SUPABASE")
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")
LANGFUSE_SECRET_KEY = os.getenv("LANGFUSE_SECRET_KEY")
LANGFUSE_PUBLIC_KEY = os.getenv("LANGFUSE_PUBLIC_KEY")
LANGFUSE_BASE_URL = os.getenv("LANGFUSE_BASE_URL")